apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.application.port }}
    protocol: TCP
    targetPort: {{ .Values.application.port }}
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP