apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: argo
spec:
  project: 'default'
  source:
    helm: {}
    repoURL: https://github.com/bernardolsp/aulao-pipeline
    targetRevision: HEAD
    path: "."
  destination:
    namespace: go-todo
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
