apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ .Release.Name }}-webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      port: "12000"
      endpoint: /
      method: POST
