apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-webhook-role
rules:
  - apiGroups:
      - '*'
    verbs:
      - "*"
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events-webhook-role
subjects:
  - kind: ServiceAccount
    name: argo-events-webhook-sa
