apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  eventBusName: default
  template:
    serviceAccountName: argo-events-webhook-sa
  dependencies:
    - name: webhook
      eventSourceName: webhook
      eventName: webhook
  triggers:
    - template:
        name: webhook-pod-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: argo
                generateName: {{ .Release.Name }}-pipeline-
              spec:
                templates: 
                  - name: clone
                    steps:
                      - - name: clone
                          templateRef:
                            name: {{ .Release.Name }}-pipeline
                            template: clone-repo